locks:
  leninkart/frontend:
    dev:
      app_key: frontend
      environment: dev
      ticket: SCRUM-43
      run_id: '23952004153'
      run_url: https://github.com/Leninfitfreak/deployment-poc/actions/runs/23952004153
      requested_version: latest-dev
      resolved_version: '23817030783'
      actor: Leninfitfreak
      runner_name: leninkar-runner
      repository: Leninfitfreak/deployment-poc
      workflow_name: Deploy From Jira
      acquired_at: '2026-04-03T15:41:19+00:00'
      last_updated_at: '2026-04-03T15:41:19+00:00'
      status: in_progress
  leninkart/product-service:
    dev:
      app_key: product-service
      environment: dev
      ticket: SCRUM-42
      run_id: '23818019006'
      run_url: https://github.com/Leninfitfreak/deployment-poc/actions/runs/23818019006
      requested_version: latest-dev
      resolved_version: '23817402173'
      actor: Leninfitfreak
      runner_name: leninkar-runner
      repository: Leninfitfreak/deployment-poc
      workflow_name: Deploy From Jira
      acquired_at: '2026-03-31T20:31:42+00:00'
      last_updated_at: '2026-03-31T20:37:01+00:00'
      status: released
      released_at: '2026-03-31T20:37:01+00:00'
      note: deployed
  leninkart/order-service:
    dev:
      app_key: order-service
      environment: dev
      ticket: SCRUM-35
      run_id: '23703000558'
      run_url: https://github.com/Leninfitfreak/deployment-poc/actions/runs/23703000558
      requested_version: latest-dev
      resolved_version: '23702948455'
      actor: Leninfitfreak
      runner_name: leninkar-runner
      repository: Leninfitfreak/deployment-poc
      workflow_name: Deploy From Jira
      acquired_at: '2026-03-29T06:17:33+00:00'
      last_updated_at: '2026-03-29T06:28:26+00:00'
      status: released
      released_at: '2026-03-29T06:28:26+00:00'
      note: 'failure: Timed out waiting for ArgoCD app ''dev-order-service'' to reach
        revision ''75a4ebe9e27f3e53141662989cfb98d86036581c'' with Sync=Synced and
        Health=Healthy'
