deployments:
  leninkart/frontend:
    dev:
      last_version: '23599512080'
      last_requested_version: v2
      last_gitops_commit: b7cfab31eb9fb33ff68d6262bfaa18d1558f19cd
      last_ticket: SCRUM-20
      last_argocd_app: frontend-dev
      last_changed_file: applications/frontend/helm/values-dev.yaml
      last_deployed_at: '2026-03-27T17:57:49+00:00'
      last_status: success
      last_action: already_deployed
      last_sync_status: Synced
      last_health_status: Healthy
      previous_successful_version: null
      previous_successful_gitops_commit: null
      rollback_source_version: null
  leninkart/product-service:
    dev:
      last_version: '23599512382'
      last_requested_version: latest-dev
      last_gitops_commit: c11855a113b4b3638c282b5e852eb382147c9594
      last_ticket: SCRUM-27
      last_argocd_app: dev-product-service
      last_changed_file: applications/product-service/helm/values-dev.yaml
      last_deployed_at: '2026-03-29T02:03:38+00:00'
      last_status: success
      last_action: already_deployed
      last_sync_status: Synced
      last_health_status: Healthy
      previous_successful_version: '23599211809'
      previous_successful_gitops_commit: 67f00d07fdbfa49c6db4dc12dbfb5cbd7684b412
      rollback_source_version: null
  leninkart/order-service:
    dev:
      last_version: '23599512459'
      last_requested_version: v2
      last_gitops_commit: 9fbcbe2c14dd42b4338df5ecf7b0f9ac11ccc998
      last_ticket: SCRUM-22
      last_argocd_app: dev-order-service
      last_changed_file: applications/order-service/helm/values-dev.yaml
      last_deployed_at: '2026-03-27T18:07:32+00:00'
      last_status: success
      last_action: deployed
      last_sync_status: Synced
      last_health_status: Healthy
      previous_successful_version: '23599211965'
      previous_successful_gitops_commit: b7cfab31eb9fb33ff68d6262bfaa18d1558f19cd
      rollback_source_version: null
