deployments:
  leninkart/frontend:
    dev:
      last_version: '23817030783'
      last_requested_version: latest-dev
      last_gitops_commit: b7843d7635c4b2864ff28760e0af78785d4b2935
      last_ticket: SCRUM-43
      last_argocd_app: frontend-dev
      last_changed_file: applications/frontend/helm/values-dev.yaml
      last_deployed_at: '2026-04-03T15:43:02+00:00'
      last_status: success
      last_action: deployed
      last_sync_status: Synced
      last_health_status: Healthy
      previous_successful_version: '23599512080'
      previous_successful_gitops_commit: b7cfab31eb9fb33ff68d6262bfaa18d1558f19cd
      rollback_source_version: null
  leninkart/product-service:
    dev:
      last_version: '23817402173'
      last_requested_version: latest-dev
      last_gitops_commit: 139ed5e9b0ae40857b38080172bc6a5835d165a5
      last_ticket: SCRUM-51
      last_argocd_app: dev-product-service
      last_changed_file: applications/product-service/helm/values-dev.yaml
      last_deployed_at: '2026-04-03T17:20:25+00:00'
      last_status: success
      last_action: already_deployed
      last_sync_status: Synced
      last_health_status: Healthy
      previous_successful_version: '23812493467'
      previous_successful_gitops_commit: b9d8297dd74e9b3b91cb9ae0417b3d46b03b15e6
      rollback_source_version: null
  leninkart/order-service:
    dev:
      last_version: '23816583483'
      last_requested_version: latest-dev
      last_gitops_commit: 0744701b8a3bf6dab5ffdec35417d041647b98e6
      last_ticket: SCRUM-60
      last_argocd_app: dev-order-service
      last_changed_file: applications/order-service/helm/values-dev.yaml
      last_deployed_at: '2026-04-05T14:18:54+00:00'
      last_status: success
      last_action: already_deployed
      last_sync_status: Synced
      last_health_status: Healthy
      previous_successful_version: '23599512459'
      previous_successful_gitops_commit: 9fbcbe2c14dd42b4338df5ecf7b0f9ac11ccc998
      rollback_source_version: null
