services:
  frontend:
    dev:
      latest: "23817030783"
      image: "leninfitfreak/frontend"
      updated_at: "2026-03-31T20:18:19Z"
      source_repo: "Leninfitfreak/leninkart-frontend"
      source_branch: "dev"
  product-service:
    dev:
      latest: "23817402173"
      image: "leninfitfreak/product-service"
      updated_at: "2026-03-31T20:30:53Z"
      source_repo: "Leninfitfreak/leninkart-product-service"
      source_branch: "dev"
  order-service:
    dev:
      latest: "23816583483"
      image: "leninfitfreak/order-service"
      updated_at: "2026-03-31T20:08:46Z"
      source_repo: "Leninfitfreak/leninkart-order-service"
      source_branch: "dev"
