services:
  frontend:
    dev:
      latest: "23701721483"
      image: "leninfitfreak/frontend"
      updated_at: "2026-03-29T04:52:14Z"
      source_repo: "Leninfitfreak/leninkart-frontend"
      source_branch: "dev"
  product-service:
    dev:
      latest: "23812493467"
      image: "leninfitfreak/product-service"
      updated_at: "2026-03-31T18:12:54Z"
      source_repo: "Leninfitfreak/leninkart-product-service"
      source_branch: "dev"
  order-service:
    dev:
      latest: "23702948455"
      image: "leninfitfreak/order-service"
      updated_at: "2026-03-29T06:13:42Z"
      source_repo: "Leninfitfreak/leninkart-order-service"
      source_branch: "dev"
