projects:
  leninkart:
    description: LeninKart e-commerce platform
    gitops_repo: https://github.com/Leninfitfreak/leninkart-infra.git
    branch_by_env:
      dev: dev
    default_app_by_env:
      dev: frontend
    allowed_apps:
      - frontend
      - product-service
      - order-service

